on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@main

      - run: |
          echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
          echo "BUILD_DATE=$(git show -s --date=format:%Y%m%d-%H%M --format=%cd)" >> $env:GITHUB_ENV
          (Get-Content d3d9\d3d9.vcxproj) -replace "Version>8.1", "Version>10.0.17763.0" | Out-File d3d9\d3d9.vcxproj
          (Get-Content LeagueLoader\Version.cs) -replace 'int\s*BUILD_NUMBER.*;', 'string BUILD_NUMBER = "${{ env.BUILD_DATE }}";' | Out-File LeagueLoader\Version.cs

      - uses: microsoft/setup-msbuild@v1.1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build solution
        run: msbuild league-loader.sln -t:restore,build -m /p:Platform="x86" /p:Configuration=Release

      - name: Build @default plugin
        run: |
          cd plugins/@default
          npm i -g pnpm@latest
          pnpm install --no-frozen-lockfile
          pnpm build
          cd ../..

      - name: Upload build outputs
        uses: actions/upload-artifact@v3
        with:
          name: league-loader-${{ env.SHORT_SHA }}-${{ env.BUILD_DATE }}
          path: |
            bin/*.exe
            bin/*.dll
            bin/plugins/
